services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: artgallery
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3308:3306"
    volumes:
      - mysql-data-artopia:/var/lib/mysql # volume added here

  backend:
    container_name: springboot-artopia
    build:
      context: ./ART_GALLERY_BACKEND
      dockerfile: ../DOCKER_FULLSTACK/backend.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react-artopia
    build:
      context: ./frontend
      dockerfile: ../DOCKER_FULLSTACK/frontend.Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data-artopia:
